# 数据生成配置
data:
  train:
    n_samples: 1000
    v0_range: [0.5, 2.0]
    a_range: [0.1, 0.5]
  test_in:
    n_samples: 200
    v0_range: [0.5, 2.0]
    a_range: [0.1, 0.5]
  test_out:
    n_samples: 200
    v0_range: [2.0, 3.0]
    a_range: [0.5, 1.0]

# 模型配置
model:
  name: "Qwen/Qwen2.5-0.5B-Instruct"
  max_length: 512

# 训练配置
training:
  batch_size: 8
  learning_rate: 1e-5
  num_epochs: 10
  save_steps: 100

# 测试配置
testing:
  model_checkpoint_path: "checkpoints/best_model"  # 训练好的模型路径
  batch_size: 8
  num_samples: 100  # 用于可视化的样本数量
  visualization:
    figure_size: [10, 6]
    dpi: 100

# 可视化配置
visualization:
  wandb:
    project: "motion-prediction-rl"
    entity: ""  # 替换为您的wandb用户名
  plotting:
    figure_size: [12, 6]
    style: "seaborn"
    dpi: 100