# 数据生成配置
data:
  train:
    n_samples: 50
    v0_range: [0.5, 2.0]
    a_range: [0.1, 0.5]
  test_in:
    n_samples: 20
    v0_range: [0.5, 2.0]
    a_range: [0.1, 0.5]
  test_out:
    n_samples: 20
    v0_range: [2.0, 3.0]
    a_range: [0.5, 1.0]

# 实验配置
project: "NLP"
experiment_name: "qwen-motion-training"
swanlab:
  log_dir: "./logs"
  metrics_update_interval: 10  # 每10步更新一次指标
  save_model_interval: 200     # 每100步保存一次模型

# 模型配置
model:
  name: "/root/NLP2025/Qwen"
  max_length: 800

# 训练配置
training:
  output_dir: "/root/autodl-tmp/result"
  run_name: "qwen-motion-training"
  learning_rate: 0.000001
  num_train_epochs: 10
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 4
  fp16: True

  beta: 0.04
  epsilon: 0.2
  num_iterations: 1
  loss_type: "bnpo"
  scale_rewards: True
  reward_weights: [5, 1]

  max_prompt_length: 350
  max_completion_length: 400
  num_generations: 4
  temperature: 0.7
  top_p: 0.9

  logging_steps: 1
  save_steps: 100
  log_completions: True
  report_to: "none"
  
  disable_dropout: True
  mask_truncated_completions: False

  save_strategy: "steps"
  save_total_limit: 2        # 只保留最新的2个checkpoint
  save_safetensors: true     # 使用更安全的safetensors格式
